const cargos = [
    { label: "Enfermeiro (a)" },
    { label: "Tecnico (a) de Enfermagem" },
    { label: "Encarregado de Estoque" },
    { label: "Farmaceutico (a)" },
    { label: "Auxiliar de Higienização" },
    { label: "Nutricionista" },
    { label: "Diretor Executivo" },
    { label: "Fisioterapeuta I" },
    { label: "Aux. de Cozinha" },
    { label: "Coordenador (a) de comunicação" },
    { label: "Assistente Social" },
    { label: "Assist. Administrativo (a)" },
    { label: "Fisioterapeuta III" },
    { label: "Medico Neurologista" },
    { label: "Tecnico de manutenção" },
    { label: "Médico Clínico" },
    { label: "Auxiliar de Farmacia" },
    { label: "Auxiliar de Cozinha" },
    { label: "Psicologo(a)" },
    { label: "Gerente de Atendimento" },
    { label: "Analista Administrativo" },
    { label: "Aux. de lavanderia" },
    { label: "Fisioterapeuta II" },
    { label: "Cozinheiro (a)" },
    { label: "Encarregado de Lavanderia" },
    { label: "Assistente de Relações Públicas" },
    { label: "Coordenador de RH" },
    { label: "Analista de Compras" },
    { label: "Administrador(a) Financeiro" },
    { label: "Motorista" },
    { label: "Auxiliar de Dieta" },
    { label: "Encarregado de Manutenção" },
  ];
  const estadosBrasileiros = [
    { label: "Acre" },
    { label: "Alagoas" },
    { label: "Amapá" },
    { label: "Amazonas" },
    { label: "Bahia" },
    { label: "Ceará" },
    { label: "Distrito Federal" },
    { label: "Espírito Santo" },
    { label: "Goiás" },
    { label: "Maranhão" },
    { label: "Mato Grosso" },
    { label: "Mato Grosso do Sul" },
    { label: "Minas Gerais" },
    { label: "Pará" },
    { label: "Paraíba" },
    { label: "Paraná" },
    { label: "Pernambuco" },
    { label: "Piauí" },
    { label: "Rio de Janeiro" },
    { label: "Rio Grande do Norte" },
    { label: "Rio Grande do Sul" },
    { label: "Rondônia" },
    { label: "Roraima" },
    { label: "Santa Catarina" },
    { label: "São Paulo" },
    { label: "Sergipe" },
    { label: "Tocantins" },
  ];
  const ccusto = [
    { label: "Clinica" },
    { label: "Administrativo" },
    { label: "Geral-Obra" },
  ];
  const tipoConta = [
    { label: "Conta Corrente" },
    { label: "Conta Salário" },
    { label: "Conta Poupança" },
  ];
  const situacao = [
    { label: "Ativo" },
    { label: "Inativo" },
    { label: "Pendente" },
  ];
  const raca = [
    { label: "Branca" },
    { label: "Preta" },
    { label: "Parda" },
    { label: "Amarela" },
    { label: "Indigena" },
       
  ]
  const estado_civil = [
    { label: "Solteiro(a)" },
    { label: "Casado(a)" },
    { label: "Divorciado(a)" },
    { label: "Viúvo(a)" },
    { label: "Separado(a)" },    
  ]